### ISSUE TITLE
刷新页面 菜单会叠加在一起

### ISSUE THREAD

**Issue by pomeloking01** [lijunping365/Open-Job-Dashboard#1]
![image](https://github.com/lijunping365/Open-Job-Dashboard/assets/53213261/40cbcdd3-a35b-46c6-9443-897485099d60)

**Comment by lijunping365** [comment]
嗯嗯 目前是有这个问题，可能是 ssr  导致的，我找找解决方案

**Comment by lijunping365** [comment]
目前已通过 关闭 ssr 的方式解决了该问题，但是后面还得观察效果

**Comment by lijunping365** [comment]
问题已找到，这里写错了，所以不用关闭 ssr 了
![image](https://github.com/lijunping365/Open-Job-Dashboard/assets/53156279/f34edafb-802d-4940-abd2-0a148370d3d9)
